#!/usr/bin/env bash
# daily-health-summary.sh - Generate and send daily health summary via Telegram
# Intended to run via systemd timer daily at 08:00 (homelab-daily-summary.timer)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="${ROOT_DIR}/.env"

load_env() {
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo "ERROR: .env not found at $f" >&2
    exit 1
  fi
  while IFS='=' read -r key val; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    val="${val#\"}" val="${val%\"}"
    val="${val#\'}" val="${val%\'}"
    export "$key=$val"
  done < "$f"
}

load_env "$ENV_FILE"

# Required
: "${TELEGRAM_BOT_TOKEN:?TELEGRAM_BOT_TOKEN not set}"
: "${TELEGRAM_CHAT_ID:?TELEGRAM_CHAT_ID not set}"


generate_summary() {
  local date_str=$(date '+%Y-%m-%d %H:%M:%S')
  local hostname=$(hostname)
  
  # Get system metrics
  local mem_info=$(free -h | awk '/Mem:/ {print $3 "/" $2}')
  local disk_nas=$(df -h /mnt/nas | awk 'NR==2 {print $3 "/" $2 " (" $5 ")"}')
  local cpu_temp=$(vcgencmd measure_temp 2>/dev/null | cut -d= -f2 | cut -d"'" -f1 || echo "N/A")
  
  # Get container status
  local total_containers=$(docker ps -q | wc -l)
  local running_containers=$(docker ps --filter "status=running" -q | wc -l)
  
  # Get backup info
  local restic_bin="${HOME}/bin/restic"
  if command -v restic >/dev/null 2>&1; then
    restic_bin=$(command -v restic)
  fi
  local last_backup=$("$restic_bin" snapshots --latest 1 --json 2>/dev/null | jq -r '.[0].time' 2>/dev/null | cut -dT -f1 || echo "Unknown")
  
  cat <<EOF
🏠 <b>Daily Homelab Health Summary</b>
📅 <b>Date:</b> $date_str
🖥️ <b>Host:</b> $hostname

📊 <b>System Metrics</b>
• Memory: $mem_info
• NAS Disk: $disk_nas
• CPU Temp: ${cpu_temp}°C

🐳 <b>Containers</b>
• Running: $running_containers / $total_containers

💾 <b>Backup</b>
• Last Snapshot: $last_backup

🤖 <i>Generated by homelab-ops-mesh daily summary</i>
EOF
}

send_telegram() {
  local message="$1"
  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -d chat_id="${TELEGRAM_CHAT_ID}" \
    -d text="$message" \
    -d parse_mode="HTML" \
    -d disable_web_page_preview="true" >/dev/null
}

main() {
  local summary=$(generate_summary)
  send_telegram "$summary"
  echo "Daily health summary sent at $(date)"
}

main "$@"