#!/usr/bin/env python3
"""Tinybot health report - sends system status to Telegram."""
import os
import json
import subprocess
import urllib.request
from datetime import datetime

TINYBOT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(TINYBOT_ROOT, ".env")


def load_env(path):
    data = {}
    if not os.path.exists(path):
        return data
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                data[key.strip()] = val.strip().strip('"').strip("'")
    return data


_env = load_env(ENV_PATH)
BOT_TOKEN = _env.get("TELEGRAM_BOT_TOKEN") or os.environ.get("TELEGRAM_BOT_TOKEN")
CHAT_ID = _env.get("TELEGRAM_CHAT_ID") or os.environ.get("TELEGRAM_CHAT_ID")


def run(cmd):
    try:
        return subprocess.check_output(cmd, timeout=10).decode().strip()
    except Exception:
        return "N/A"


def send_telegram(token, chat_id, text):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = json.dumps({"chat_id": chat_id, "text": text, "parse_mode": "HTML"}).encode()
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def main():
    if not BOT_TOKEN or not CHAT_ID:
        print("TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set")
        return

    uptime = run(["uptime", "-p"])
    temp_raw = run(["cat", "/sys/class/thermal/thermal_zone0/temp"])
    if temp_raw != "N/A":
        try:
            temp_c = round(int(temp_raw) / 1000, 1)
            temp_str = f"{temp_c}°C"
        except ValueError:
            temp_str = "N/A"
    else:
        temp_str = "N/A"

    disk = run(["sh", "-c", "df -h / | tail -1 | awk '{print $3, \"/\", $2, \"(\", $5, \")\"}'"])
    mem = run(["sh", "-c", "free -h | grep Mem | awk '{print $3, \"/\", $2}'"])
    load = run(["cat", "/proc/loadavg"])

    total = run(["sh", "-c", "docker ps -q | wc -l"])
    running = run(["sh", "-c", "docker ps --filter status=running -q | wc -l"])

    msg = f"""<b>Homelab Health Report</b> — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}

<b>System</b>
Uptime: {uptime}
Temp: {temp_str}
Disk: {disk}
Memory: {mem}
Load: {load}

<b>Containers</b>
Running: {running} / {total}

<i>Generated by homelab-ops-mesh</i>"""

    try:
        send_telegram(BOT_TOKEN, CHAT_ID, msg)
        print(f"Report sent to {CHAT_ID}")
    except Exception as e:
        print(f"Failed to send: {e}")


if __name__ == "__main__":
    main()
