[global]
   workgroup = HOMELAB
   server string = AutoBot NAS
   security = user
   map to guest = Never
   server min protocol = SMB2_10
   server max protocol = SMB3_11
   server signing = mandatory
   smb encrypt = desired
   disable netbios = yes
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   ea support = yes
   vfs objects = catia fruit streams_xattr
   fruit:metadata = stream
   fruit:resource = stream
   fruit:locking = none
   unix extensions = no
   log file = /dev/stdout
   max log size = 0
   logging = files

[samba]
   comment = NAS root share
   path = /mnt/nas
   browseable = yes
   read only = no
   valid users = vansh
   force user = vansh
   force group = vansh
   create mask = 0664
   directory mask = 0775
   guest ok = no
