server:
    interface: 0.0.0.0@5053
    access-control: 127.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: ::1 allow
    access-control: 0.0.0.0/0 refuse
    access-control: ::0/0 refuse
    do-daemonize: no
    do-ip6: no
    username: ""
    hide-identity: yes
    hide-version: yes
    use-syslog: no
    logfile: ""
    verbosity: 1
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
    module-config: "iterator"

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8953
    control-use-cert: no

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 8.8.8.8@853#dns.google
